### ISSUE TITLE
BTCP wrong Network Difficulty

### ISSUE THREAD

**Issue by dmshel** [coinfoundry/miningcore#283] opened 2018-03-24 16:05 UTC
{
  "version": 1001051,
  "protocolversion": 180003,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 291384,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 175883.2527040516,
  "testnet": false,
  "keypoololdest": 1521887064,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
![default](https://user-images.githubusercontent.com/37098267/37866067-dc285282-2fb7-11e8-9bcd-801d387c8755.JPG)

**Comment by Gadflyii** [comment] 2018-03-24 16:47
It is showing the correct network difficulty. The Daemon-cli interface runs a calculation to display the legacy network diff. Search issues and you will find the issue I opened with links to the BTCP Github with more info.

**Comment by dmshel** [comment] 2018-03-24 16:59
can i see link?

**Comment by calvintam236** [comment] 2018-03-24 19:58
Duplicate of #279 .

**Closed by calvintam236** 2018-03-24 19:58 UTC
