### ISSUE TITLE
zcash error in payment ：Newtonsoft.Json

### ISSUE THREAD

**Issue by lucas556** [coinfoundry/miningcore#203] opened 2018-02-08 02:00 UTC
When I test in zcash testnet, there is always the following error.

server os：ubuntu 16.04 x64
coin : zcash testnet

> [2018-02-08 09:46:28.3833] [I] [zec] [ZCash Payout Handler] Unlocked block 191497 worth 10 ZEC 
[2018-02-08 09:46:28.3833] [I] [zec] [ZCash Payout Handler] Unlocked block 191498 worth 10 ZEC 
[2018-02-08 09:46:28.5147] [I] [PayoutManager] Processing payments for pool zec, block 191156 
[2018-02-08 09:46:28.5147] [I] [zec] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
[2018-02-08 09:46:28.5987] [E] [PayoutManager] [zec] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /pool/src/MiningCore/DaemonInterface/DaemonClient.cs:line 380
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__8.MoveNext() in /pool/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<UpdateBlockRewardBalancesAsync>d__6.MoveNext() in /pool/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Extensions.ConnectionFactoryExtensions.<RunTxAsync>d__8.MoveNext() in /pool/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 95    at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x) in /pool/src/MiningCore/DaemonInterface/DaemonClient.cs:line 380
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__8.MoveNext() in /pool/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<UpdateBlockRewardBalancesAsync>d__6.MoveNext() in /pool/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Extensions.ConnectionFactoryExtensions.<RunTxAsync>d__8.MoveNext() in /pool/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /pool/src/MiningCore/Payments/PayoutManager.cs:line 95
[2018-02-08 09:46:32.8620] [I] [zec] [Pool] [0HLBE3LI0Q2R2] Share accepted: D=1

**Comment by lucas556** [comment] 2018-02-08 02:03
My Configuration is: 

{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "LOG1.log",
        "logBaseDirectory": "logbas.log",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 43653,
            "user": "test",
            "password": "test",
            "database": "miningcore"
        }
    },
    "equihashMaxThreads": 4,
        "devDonation": 0.0,
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
        "api": {
    "enabled": true,
    "listenAddress": "10.20.3.3",
    "port": 8080
    },
    "pools": [{
        "id": "zec",
        "enabled": true,
        "coin": {
            "type": "ZEC"
        },
        "address": "tmJAmQdiBDKaAnKYh18Z1LNLAuwABtA59XY",
        "z-address": "ztRYC7HA1nYZVFRzLATywWJdTwoTkZKnyYpoa4YhoahHtbuK3nkUVZbAa35MK2j8pvDbN954VBzW2K2fVtNKL9ewoZz8G4t",
        "rewardRecipients": [
            {
                "type": "op",
                "address": "tmMG5waE2rRet97JGuA7aznTXiuk1jRzb5z",
                "percentage": 2
            }
        ],
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout": 10,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3392": {
                "listenAddress": "10.20.3.3",
                "difficulty": 0.1,
                "varDiff": {
                    "minDiff": 0.01,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,
                    "maxDelta": 1
                }
            },
            "3393": {
                "listenAddress": "10.20.3.3",
                "difficulty": 1
            }
        },
        "daemons": [
            {
                "host": "112.330.230.50",
                "port": 8555,
                "user": "test",
                "password": "test"
            }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.02,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            }
        }
    }]
}

**Comment by lucas556** [comment] 2018-02-08 02:07
and miners can not always receive payment.

**Comment by oliverw** [comment] 2018-02-09 11:41
I've observed similar errors on testnet once. It works find in production using mainnet.

**Comment by lucas556** [comment] 2018-02-09 17:17
Thank you for oliverw.
The networkDifficulty error in the Api data is also in the mainnet, meanwhile, the zcash-cli getinfo get is correct.

 "networkStats": {
    "networkHashRate": 335053392.0,
    "networkDifficulty": 1.2785081528045759E+57,
    "lastNetworkBlockTime": "2018-02-05T02:01:59.914593",
    "blockHeight": 266725,
    "connectedPeers": 11
  },

Will oliverw, networkDifficulty mistakes will affect mining?

**Comment by saltyminer** [comment] 2018-02-09 20:13
I believe there are two issues here:

1.) you are unlocking two blocks at one time.  This calls the zshield command twice in succession.  I believe the first call to zshield moves all funds to the zaccount and the second zshield call falls since there is nothing left to shield.  I saw similar behavior in whenever two or more blocks were found in succession, although I believe I saw different messages so it may not be the same issue.  If this is indeed a case where the second zshield command fails then you can safely ignore that.

2.) I believe the network difficulty calculated may be too high  I had a similar issue that I reported before in issue #194.  Payments won't get processed since the network difficulty recorded on shares are 1.27E+57 and your share difficulty is recorded as 1 in your example.  I need help from Oliver or someone else to help figure out if the network difficulty is being calculated properly for ZEC/HUSH.  Regardless, if you debug the PPLNS code you can see that your shares are likely not being scored because of the large discrepancy in share difficulty vs network difficulty.

**Comment by lucas556** [comment] 2018-02-10 04:18
Thank you.saltyminer.
I think the payment error is that each piece of zcash pays developers 2.5 zcash, whereas the payment address in the test network is not compatible with the address in miningcore. I do not know what to do about the network's difficulty.

**Comment by saltyminer** [comment] 2018-02-10 17:58
Hi Lucas,

I am getting the same error you posted above on "Shielding ZCash Coinbase funds".  For testing with TESTNET you can temporarily bypass the dev payout so you can debug.  I believe I have a fix for the network difficulty and am now testing the z_shieldcoinbase command to try to resolve the error you posted above.  I will open a PR after I do some more testing and let @oliverw take a look.

**Comment by lucas556** [comment] 2018-02-12 07:47
hi,@saltyminer.
z_shieldcoinbase Have you tested it?

**Comment by saltyminer** [comment] 2018-02-21 15:43
Hi Lucas,

As @oliverw mentioned, this code does work.  I wrapped the method [ZCashPayoutHandler.ShieldCoinBaseAsync](https://github.com/coinfoundry/miningcore/blob/8996c0d97c96ed46d438bf8a0245a89b5ed9459d/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs#L190) in try/catch block which allows for logging the exception and continuing execution since we really don't care about the error.

**Comment by oliverw** [comment] 2018-02-21 19:54
Should be fixed in master.

**Closed by oliverw** 2018-02-21 19:54 UTC
Labels: question

**Comment by lucas556** [comment] 2018-02-24 03:57
@saltyminer  Will you still see this mistake?

**Comment by saltyminer** [comment] 2018-02-24 05:07
@lucas556 yes, I will reply to issue #219 since it looks like a duplicate of this issue.

**Comment by lucas556** [comment] 2018-02-24 06:06
@saltyminer thank you.

**Comment by oliverw** [comment] 2018-02-24 09:05
@lucas556 @saltyminer I've commited several changes to the ZCashPayoutHandler to the dev branch yesterday. Could you try it?

**Comment by saltyminer** [comment] 2018-02-25 00:48
@oliverw I will try it soon and let you know.  Looking at the code it appears that is should handle the response now.  I saw a few minor typos that I commented on.

**Comment by lucas556** [comment] 2018-02-26 04:20
@oliverw  i try,ple waiting.

**Comment by lucas556** [comment] 2018-02-26 04:43
> 
[2018-02-26 12:31:00.3623] [I] [zec1] Adding 0.2 ZEC to balance of tmB71gN4NoEoFTmQqM5nGDcDWXqAJ3iTLdt 
[2018-02-26 12:31:00.3711] [I] [PPLNS] Fetching page 0 of shares for pool zec1, block 195510 
[2018-02-26 12:31:00.4025] [I] [PPLNS] Balance-calculation for pool zec1, block 195510 completed with accumulated score 0 (0%) 
[2018-02-26 12:31:00.4087] [I] [PayoutManager] Processing payments for pool zec1, block 195511 
[2018-02-26 12:31:00.4087] [I] [zec1] Adding 0.2 ZEC to balance of tmB71gN4NoEoFTmQqM5nGDcDWXqAJ3iTLdt 
[2018-02-26 12:31:00.4176] [I] [PPLNS] Fetching page 0 of shares for pool zec1, block 195511 
[2018-02-26 12:31:00.4489] [I] [PPLNS] Balance-calculation for pool zec1, block 195511 completed with accumulated score 0 (0%) 
[2018-02-26 12:31:00.4552] [I] [PayoutManager] Processing payments for pool zec1, block 195512 
[2018-02-26 12:31:00.4552] [I] [zec1] Adding 0.2 ZEC to balance of tmB71gN4NoEoFTmQqM5nGDcDWXqAJ3iTLdt 
[2018-02-26 12:31:00.4640] [I] [PPLNS] Fetching page 0 of shares for pool zec1, block 195512 
[2018-02-26 12:31:00.4958] [I] [PPLNS] Balance-calculation for pool zec1, block 195512 completed with accumulated score 0 (0%) 
[2018-02-26 12:31:00.5291] [I] [zec1] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
[2018-02-26 12:31:00.5528] [E] [PayoutManager] [zec1] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /root/miningcore-dev/src/MiningCore/DaemonInterface/DaemonClient.cs:line 380
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in /root/miningcore-dev/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in /root/miningcore-dev/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 97    at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /root/miningcore-dev/src/MiningCore/DaemonInterface/DaemonClient.cs:line 380
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdSingleAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<ShieldCoinbaseAsync>d__11.MoveNext() in /root/miningcore-dev/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.ZCash.ZCashPayoutHandler.<PayoutAsync>d__10.MoveNext() in /root/miningcore-dev/src/MiningCore/Blockchain/ZCash/ZCashPayoutHandler.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MiningCore.Payments.PayoutManager.<PayoutPoolBalancesAsync>d__13.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /root/miningcore-dev/src/MiningCore/Payments/PayoutManager.cs:line 97
^C[2018-02-26 12:31:01.6999] [I] [Program] SIGINT received. Exiting. 

root@VM-0-7-ubuntu:~/miningcore-dev/build# vim config.json 
root@VM-0-7-ubuntu:~/miningcore-dev/build# zcash-cli z_getbalance "ztKEzvgvhQWdJR1ic8hhjJgDDyQDxByj4K8beRVJ7rcXrqb68y59VHPh1Lr7C9U629Vy2GXK3aXjhJrxjNWFZQYc8NJGJAd" 
2266.59893625
root@VM-0-7-ubuntu:~/miningcore-dev/build# zcash-cli getinfo
{
  "version": 1001450,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 5963.16720535,
  "blocks": 196043,
  "timeoffset": 0,
  "connections": 9,
  "proxy": "",
  "difficulty": 12522.29428109101,
  "testnet": true,
  "keypoololdest": 1519603522,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": "WARNING: check your network connection, 1 blocks received in the last 4 hours (96 expected)"
}

**Comment by lucas556** [comment] 2018-02-26 04:45
@oliverw @saltyminer The above is the error log and daemon status.
ubuntu 16.04 x64
miningcore-dev

**Comment by Gadflyii** [comment] 2018-02-27 04:39
I get this exact same issue on Release 19 in both windows and Ubuntu 16.04 x64
