### ISSUE TITLE
Some Help

### ISSUE THREAD

**Issue by dmshel** [coinfoundry/miningcore#269] opened 2018-03-16 13:15 UTC
Hello
Installed the latest version from the repository, but a few previously discussed problems arose, searched for all the fixes in the code, everything is equal to
but there are errors
Help advice how to fix it
Bitcoin Gold
![default](https://user-images.githubusercontent.com/37098267/37522199-d5690698-2955-11e8-819f-6ee403f2c8c8.JPG)
This fix 46a0c84. i check code its ok. but have error at me
Where to install devDonation = 0? in what config?
Dear Oliver. Can u tellme instruction how i can modifed code for PPS and SOLO payment?

**Comment by calvintam236** [comment] 2018-03-18 08:45
Duplicate of #266 .

`devDonation` is a parent item at `config.json`. Please look at the configuration wiki page.

**Closed** 2018-03-23 20:46 UTC
Labels: duplicate
