### ISSUE TITLE
[I] [btc1] [Bitcoin Job Manager] Waiting for daemons to come online ...

### ISSUE THREAD

**Issue by dutchakdev** [coinfoundry/miningcore#235] opened 2018-03-03 12:38 UTC
Good day all! 
1. Thank you for that amazing app.
2. I have this config:
```
"daemons": [
        {
          "host": "litecoind-fork",
          "port": 9776,
          "user": "user",
          "password": "<remove>"
        },
        {
          "host": "litecoind-fork",
          "port": 9777,
          "user": "user",
          "password": "<remove>",
          "category": "wallet"
        }
      ],
```
Miningcore and litecoind runing in docker containers, and mining core have access to daemon:

```
curl --basic -u user:<removed> --digest --data-binary '{"jsonrpc": "2.0", "id":"1", "method": "getinfo", "params": [] }' -H 'content-type: application/json' -X POST http://litecoind-fork:9776/
{"result":{"version":1000000,"protocolversion":70002,"walletversion":60000,"balance":0.00000000,"blocks":97096,"timeoffset":1,"connections":3,"proxy":"","difficulty":32.97818681,"testnet":false,"keypoololdest":1520075682,"keypoolsize":101,"paytxfee":0.00000000,"mininput":0.00001000,"errors":""},"error":null,"id":"1"}
``` 

But in logs i see:

`[I] [btc1] [Bitcoin Job Manager] Waiting for daemons to come online ...`

**Comment by bitspill** [comment] 2018-03-03 12:52
How recent of a litecoind-fork is this?

In your curl test you use `getinfo` but by default MiningCore attempts to use the newer functions like `getblockchaininfo` which not all coins/forks are updated to include.

Perhaps add `"HasLegacyDaemon": true` at to the pool `btc1` section of your configfile

**Comment by dutchakdev** [comment] 2018-03-03 13:18
Hey, yes, when i call getblockchaininfo i have message:
`{"result":null,"error":{"code":-32601,"message":"Method not found"},"id":"1"}`

I added `HasLegacyDaemon: true`, but it doesn't work(

**Comment by dutchakdev** [comment] 2018-03-03 13:31
HasLegacyDaemon from uppercase strange for me, mb I made a mistake
```
    "pools": [{
      "id": "litecoind-fork",
      "enabled": true,
      "coin": {
        "type": "LTC"
      },
      "HasLegacyDaemon": true,
```

**Comment by dutchakdev** [comment] 2018-03-03 14:23
Problem like #119 
@oliverw Hey, can you help me?

**Comment by bitspill** [comment] 2018-03-03 21:22
Ah, my mistake, the H should be lowercase if you didn't already try that.

```
"pools": [{
      "id": "litecoind-fork",
      "enabled": true,
      "coin": {
        "type": "LTC"
      },
      "hasLegacyDaemon": true,
```

**Comment by dutchakdev** [comment] 2018-03-05 08:48
@bitspill doesn't work(

**Comment by calvintam236** [comment] 2018-03-05 19:36
Duplicate of #42

**Comment by rydemods** [comment] 2018-03-17 14:28
@dutchakdev  try installing bitcoin-qt

**Comment by oliverw** [comment] 2018-03-17 14:44
<code>"hasLegacyDaemon": true </code> should work fine.

**Comment by dutchakdev** [comment] 2018-03-19 12:37
@rydemods its fork of litecoin

**Comment by oliverw** [comment] 2018-03-23 20:54
@dutchakdev Made any progress?

**Comment by dutchakdev** [comment] 2018-03-25 13:37
@oliverw doesn't work for me(

**Closed** 2018-10-11 13:41 UTC
