### ISSUE TITLE
PPLNS incorrect payout?

### ISSUE THREAD

**Issue by Serpent6877** [coinfoundry/miningcore#52] opened 2017-11-06 07:11 UTC
I have an ETC config. 

```
   "pools": [{
      "id": "etc1",
      "enabled": true,
      "coin": {
        "type": "ETC"
      },
      "address": "0x3ff93f45e06a0dd7d8acb7d6f5ef2b5d7bfe4ab7",
      "rewardRecipients": [
        {
          "type": "op",
          "address": "0x3ff93f45e06a0dd7d8acb7d6f5ef2b5d7bfe4ab7",
          "percentage": 0
        }
      ],

     "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.50,
        "minimumPaymentToPaymentId": 1.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }

```

I am the only miner on this pool during testing with 300MH. A block was found by me. But my pending balance is:

 "pendingShares": 56139,
  "pendingBalance": 0.421189398082,
  "totalPaid": 0.0,

This is on Linux using Claymore. So there is the small dev fee connection. Is it really causing that much of a loss?

**Comment by oliverw** [comment] 2017-11-06 07:29
The problem is the large window size combined with few shares required to find the block. The algorithm was unable to hit the PPLNS window size (factor": 2.0) resulting in a staggered payout over multiple blocks. 

To be clear, you did not lose anything, it's just that you get paid over multiple blocks. I'd try reducing the window size down to 0.5 or even less. You need to experiment a bit.

**Comment by Serpent6877** [comment] 2017-11-06 17:58
Is 2.0 good for larger pools then? And the low payout is due to my low share/hashing power?

Thanks for the quick reply by the way.

**Comment by oliverw** [comment] 2017-11-06 18:07
The low payout is simply because of the few number of shares contributing to the block you found. And yes 2.0 would be for pools with lots of miners generating tons of shares. In general PPLNS is not really suited to solo-mining. That's why we have a [PROP payout scheme](https://github.com/coinfoundry/miningcore/issues/19) on the todo list. If you'd like to manually force the pool to send yourself the entire block reward do this:

Open the postgres command line client: psql
```
select sum(reward) from blocks where status = 'confirmed';
update balances set amount = <result from previous query> where address = 'your address';
```
Make sure to start the pool. And of course never do that on a production pool with real miners 😄

**Comment by Serpent6877** [comment] 2017-11-06 18:44
Thanks. This seems to have broke a couple of things. When I look at my miner API I only see this now:

{
  "pendingShares": 62756,
  "pendingBalance": 5.0,
  "totalPaid": 0.0,
  "hashrate": []
}

And I get this error in the logs:

[2017-11-06 10:37:34.6744] [E] [etc1] [Ethereum Payout Handler] Object reference not set to an instance of an object.

Here is what I ran in psql:
select sum(reward) from blocks where status = 'confirmed';

# output
      sum       
----------------
 5.000000000000
(1 row)

update balances set amount = 5.000000000000 where address = '0x24a0dc797d584f13b92ffcee41449b0f4e6427e6';

**Comment by oliverw** [comment] 2017-11-06 18:46
Can you post the full exception log including stacktrace?

**Comment by Serpent6877** [comment] 2017-11-06 18:52
Not sure if this is what you are asking for?

[2017-11-06 10:50:11.1624] [I] [ShareRecorder] Online 
[2017-11-06 10:50:11.2280] [I] [ApiServer] Launching ... 
[2017-11-06 10:50:11.5772] [I] [ApiServer] Online @ 107.191.112.238:4000 
[2017-11-06 10:50:11.6287] [I] [etc1] [Pool] Launching ... 
[2017-11-06 10:50:11.6662] [I] [etc1] [Ethereum Job Manager] Launching ... 
[2017-11-06 10:50:11.8483] [I] [etc1] [Ethereum Job Manager] All daemons online 
[2017-11-06 10:50:11.8690] [I] [etc1] [Ethereum Job Manager] All daemons synched with blockchain 
[2017-11-06 10:50:11.9961] [D] [EthashFull] No pre-generated DAG available, creating new for epoch 159 
[2017-11-06 10:50:11.9972] [D] [EthashFull] Pre-generating DAG for epoch 160 
[2017-11-06 10:50:12.0041] [I] [Dag] Generating DAG for epoch 160 
[2017-11-06 10:50:12.0041] [I] [Dag] Generating DAG for epoch 159 
[2017-11-06 10:50:14.9705] [I] [Dag] Done generating DAG for epoch 160 after 00:00:02.9660889 
[2017-11-06 10:50:15.0486] [I] [Dag] Done generating DAG for epoch 159 after 00:00:03.0441188 
[2017-11-06 10:50:15.0672] [I] [etc1] [Ethereum Job Manager] Online 
[2017-11-06 10:50:16.1348] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:50:16.1520] [I] [etc1] [Pool] Stratum port 107.191.112.238:3333 online 
[2017-11-06 10:50:16.1977] [I] [etc1] [Pool] Online 
[2017-11-06 10:50:16.2033] [I] [etc1] 

Mining Pool:            etc1 
Coin Type:              ETC 
Network Connected:      Classic
Detected Reward Type:   POW
Current Block Height:   4788248
Current Connect Peers:  20
Network Difficulty:     113888633238289
Network Hash Rate:      0 KH/s
Stratum Port(s):        3333
Pool Fee:               0%
 
[2017-11-06 10:50:16.2120] [I] [PayoutManager] Online 
[2017-11-06 10:50:16.2165] [I] [PayoutManager] Processing payments for pool etc1 
[2017-11-06 10:50:16.9338] [I] [PayoutManager] No updated blocks for etc1 
[2017-11-06 10:50:17.0682] [E] [etc1] [Ethereum Payout Handler] Object reference not set to an instance of an object. 
[2017-11-06 10:50:20.0962] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:50:29.0931] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:50:34.3665] [I] [etc1] [Pool] [0HL958SVSQL5N] Share accepted: D=858993459.2 
[2017-11-06 10:50:35.2163] [I] [etc1] [Pool] [0HL958SVSQL5N] Share accepted: D=858993459.2 
[2017-11-06 10:50:39.0902] [I] [etc1] [Ethereum Job Manager] New block detected

**Comment by oliverw** [comment] 2017-11-06 18:55
No I meant everything following: [2017-11-06 10:37:34.6744] [E] [etc1] [Ethereum Payout Handler] Object reference not set to an instance of an object.

**Comment by Serpent6877** [comment] 2017-11-06 18:58
it is just normal runtime info until payout again. Then repeats the same error. No other info.

[2017-11-06 10:37:33.8480] [I] [PayoutManager] Online 
[2017-11-06 10:37:33.8543] [I] [PayoutManager] Processing payments for pool etc1 
[2017-11-06 10:37:34.5558] [I] [PayoutManager] No updated blocks for etc1 
[2017-11-06 10:37:34.6744] [E] [etc1] [Ethereum Payout Handler] Object reference not set to an instance of an object. 
[2017-11-06 10:37:45.7563] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:37:47.5950] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:37:48.2838] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:37:53.8877] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:37:56.7592] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:37:58.1377] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:03.1868] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:08.5573] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:11.7632] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:38:12.3096] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:14.7867] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:16.7189] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:18.2759] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:18.3536] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:20.3002] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:23.8850] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:28.5505] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:38:31.8596] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:32.9852] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:40.5302] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:38:42.7747] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:38:43.4483] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:45.6053] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:47.3736] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:38:50.5188] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:54.7748] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:38:55.2736] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:38:56.1536] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:56.2978] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:57.7823] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:38:58.1852] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:39:03.3609] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:39:04.7751] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:17.7569] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:19.2071] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:39:20.4824] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:39:26.4862] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=858993459.2 
[2017-11-06 10:39:27.3466] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:39:29.2275] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:39:34.3319] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=858993459.2 
[2017-11-06 10:39:36.6265] [I] [etc1] [Pool] [0HL958LPQ0AV9] VarDiff update to 0.310687655343828 
[2017-11-06 10:39:36.6575] [I] [etc1] [Pool] [0HL958LPQ0AVA] VarDiff update to 0.702648516474766 
[2017-11-06 10:39:36.7523] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:40.7533] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:45.3962] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=3017852398.842 
[2017-11-06 10:39:45.4695] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=3017852398.842 
[2017-11-06 10:39:46.7557] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:54.7553] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 10:39:57.6085] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=3017852398.842 
[2017-11-06 10:40:13.7553] [I] [etc1] [Pool] [0HL958LPQ0AVA] Share accepted: D=3017852398.842 
[2017-11-06 10:40:16.3610] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=1334393318.973 
[2017-11-06 10:40:20.7298] [I] [etc1] [Pool] [0HL958LPQ0AV9] Share accepted: D=1334393318.973 
[2017-11-06 10:40:21.7524] [I] [etc1] [Ethereum Job Manager] New block detected

**Comment by oliverw** [comment] 2017-11-06 19:00
Do you have per-pool logging turned on in the config?

**Comment by Serpent6877** [comment] 2017-11-06 19:01
"logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "pool.log",
        "logBaseDirectory": "/opt/devpool/logs",
        "perPoolLogFile": false
    },

**Comment by oliverw** [comment] 2017-11-06 19:02
Hmm, strange that the exception contains no stacktrace.

**Comment by oliverw** [comment] 2017-11-06 19:09
Could you update to the latest version and try again. The error should be more detailed now.

**Comment by Serpent6877** [comment] 2017-11-06 19:35
[2017-11-06 11:35:27.9402] [I] [PayoutManager] Online 
[2017-11-06 11:35:27.9453] [I] [PayoutManager] Processing payments for pool etc1 
[2017-11-06 11:35:28.6549] [I] [PayoutManager] No updated blocks for etc1 
[2017-11-06 11:35:28.7837] [E] [etc1] System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282 System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282    at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 384
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282
[2017-11-06 11:35:32.8350] [I] [etc1] [Ethereum Job Manager] New block detected 
[2017-11-06 11:35:37.8272] [I] [etc1] [Ethereum Job Manager] New block detected

**Comment by oliverw** [comment] 2017-11-06 19:49
Please update again. You will now be told where the problem lies :-)

**Comment by Serpent6877** [comment] 2017-11-06 20:03
There we go:

[2017-11-06 11:56:42.3183] [I] [ShareRecorder] Online 
[2017-11-06 11:56:42.3819] [I] [ApiServer] Launching ... 
[2017-11-06 11:56:42.7529] [I] [ApiServer] Online @ 107.191.112.238:4000 
[2017-11-06 11:56:42.7907] [E] [etc1] "paymentProcessing.coinbasePassword" pool-configuration property missing or empty (required for unlocking wallet during payment processing) 
Cluster cannot start. Good Bye!

I looked through the config info and examples but don't see what option to set for the coinbase password.

**Comment by oliverw** [comment] 2017-11-06 20:08
This options is only required for Ethereum based pools:

```
{
   "id": "eth1",
    "enabled": true,
    "coin": {
        "type": "ETH"
    },
    ...
    "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.01,
        "minimumPaymentToPaymentId": 5.0,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
            "factor": 2.0
        },
        "coinbasePassword": "<wallet password>",
        "keepUncles": false, 
        "keepTransactionFees": false
    }
},
```

keepUncles = false = payout uncles to miners (pools like nanopool do that)
keepTransactionFees = false = payout transaction fees to miners (pools like nanopool do that)

**Comment by Serpent6877** [comment] 2017-11-06 20:09
Okay. Figured out the config:

    "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.5,
        "payoutScheme": "PPLNS",
        "CoinbasePassword": "testpassword",
        "payoutSchemeConfig": {
          "factor": 1.0
        }
      }

However the following errors occurred:
 
[2017-11-06 12:08:12.2178] [I] [PayoutManager] Online 
[2017-11-06 12:08:12.2231] [I] [PayoutManager] Processing payments for pool etc1 
[2017-11-06 12:08:12.8996] [I] [PayoutManager] No updated blocks for etc1 
[2017-11-06 12:08:13.0494] [E] [etc1] System.Exception: Unable to unlock coinbase account for sending transaction
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282 System.Exception: Unable to unlock coinbase account for sending transaction
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282    at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282
[2017-11-06 12:08:29.2772] [I] [etc1] [Pool] [0HL95A8GII3KH] Share accepted: D=429496729.6 
[2017-11-06 12:08:29.9859] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:31.9955] [W] [ShareRecorder] Retry 2 in 00:00:04 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:32.0622] [I] [etc1] [Pool] [0HL95A8GII3KH] Share accepted: D=429496729.6 
[2017-11-06 12:08:33.6195] [I] [etc1] [Pool] [0HL95A8GII3KH] Share accepted: D=429496729.6 
[2017-11-06 12:08:36.0025] [W] [ShareRecorder] Retry 3 in 00:00:08 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:38.9061] [I] [etc1] [Pool] [0HL95A8GII3KH] Share accepted: D=429496729.6 
[2017-11-06 12:08:44.0146] [W] [ShareRecorder] Fallback due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:45.0490] [W] [ShareRecorder] Retry 1 in 00:00:02 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:47.0560] [W] [ShareRecorder] Retry 2 in 00:00:04 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 
[2017-11-06 12:08:51.0631] [W] [ShareRecorder] Retry 3 in 00:00:08 due to Npgsql: PostgresException (42703: column "difficulty" of relation "shares" does not exist) 

Seems some new errors started with the last pull as well.

**Comment by oliverw** [comment] 2017-11-06 20:14
Are you using the correct password for the pool's wallet on your end? It has to be correct.

The other errors are due to some recently committed db schema changes. Give me a couple minutes to come up with migration instructions.

**Comment by Serpent6877** [comment] 2017-11-06 20:17
Verified password several times. I use a password file with parity. My password does contain an exclamation in it. Not sure if that is having an effect.

Example: t3stPasw0rd!

**Comment by oliverw** [comment] 2017-11-06 20:22
Please run this in psql:

```
ALTER TABLE shares add difficulty REAL NOT NULL DEFAULT 0;
UPDATE shares set difficulty = stratumdifficulty;
ALTER TABLE shares ALTER COLUMN stratumdifficulty DROP NOT NULL;
ALTER TABLE shares ALTER COLUMN stratumdifficultybase DROP NOT NULL;
```

**Comment by Serpent6877** [comment] 2017-11-06 20:25
Okay. Looks like that corrected the new share issues. Still can't get the password to work.

**Comment by oliverw** [comment] 2017-11-06 20:27
This is how we run parity on poolmining.org:

```
/usr/bin/parity --chain $ETH_CHAIN --base-path "/data" --mode "active" --no-ui --no-dapps \
--jsonrpc-interface "0.0.0.0" --jsonrpc-threads 4 --no-discovery \
--jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --ipc-path "/data/geth.ipc" \
--nat $ETH_NAT --author $ETH_COINBASE --cache-size 512 --logging "info"
```
It is of crucial importance that the value of --author matches the pool address in MiningCore's configuration AND that --jsonrpc-apis contains "personal".

**Comment by oliverw** [comment] 2017-11-06 20:28
We definitely need better documentation for this. Sorry for that.

**Comment by Serpent6877** [comment] 2017-11-06 20:33
I have been running parity using the open ethereum pool for months and an never needed the personal setting. Interesting. That was all it needed. But this is the next error:

[2017-11-06 12:30:37.5503] [I] [PayoutManager] Online 
[2017-11-06 12:30:37.5565] [I] [PayoutManager] Processing payments for pool etc1 
[2017-11-06 12:30:38.2670] [I] [PayoutManager] No updated blocks for etc1 
[2017-11-06 12:30:38.3939] [I] [etc1] [Ethereum Payout Handler] Sending 5 ETC to 0x24a0dc797d584f13b92ffcee41449b0f4e6427e6 
2017-11-06 12:30:38  Error importing transaction: Transaction(InsufficientBalance { balance: 5000000000000000000, cost: 5018800000000000000 })
[2017-11-06 12:30:38.4737] [E] [etc1] System.Exception: eth_sendTransaction returned error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 5018800000000000000 and got: 5000000000000000000. code -32010
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282 System.Exception: eth_sendTransaction returned error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 5018800000000000000 and got: 5000000000000000000. code -32010
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282    at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<Payout>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Ethereum.EthereumPayoutHandler.<PayoutAsync>d__12.MoveNext() in /opt/devpool/miningcore/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs:line 282

Since this is the first block and there is no previous balance it does not have enough to cover the TX feels. I will adjust it to say 4.9 ETC but just to let you know. This looks much better now.

**Comment by Serpent6877** [comment] 2017-11-06 20:34
No need to be sorry about anything. You are giving your free time for a great project.

**Comment by oliverw** [comment] 2017-11-06 20:37
Yeah it's a special case since we've manually messed with the balances. Adjusting the amount as you've suggested is the correct approach here.

**Comment by Serpent6877** [comment] 2017-11-06 20:42
Thanks again. Do you have a ETC address? I'll send you a few.

**Comment by oliverw** [comment] 2017-11-06 20:44
That's the least I can do. 

0xF8cCE9CE143C68d3d4A7e6bf47006f21Cfcf93c0

**Comment by Serpent6877** [comment] 2017-11-06 20:47
2 incoming from 0x24a0dc797d584f13b92ffcee41449b0f4e6427e6. Can close this issue now. Thanks!

**Closed** 2017-11-06 20:50 UTC

**Comment by oliverw** [comment] 2017-11-06 20:54
Wow. That wasn't necessary but thanks a lot!

**Comment by oliverw** [comment] 2017-11-16 12:51
@Serpent6877 One question. Was the block you mentioned in your opening post found on the mainnet?

**Comment by Serpent6877** [comment] 2017-11-16 16:36
@oliverw Classic

**Comment by oliverw** [comment] 2017-11-16 16:37
@Serpent6877 But it was not a testnet right?

**Comment by Serpent6877** [comment] 2017-11-17 00:41
@oliverw Correct. This was a full ETC production system. I am mining it with my 240Mh test system.

**Comment by oliverw** [comment] 2017-11-17 07:23
@Serpent6877 Thanks for the info. I was just asking because our pool hasn't found a single ETH or ETC block ever in production 😞

**Comment by Serpent6877** [comment] 2017-11-17 18:01
@oliverw I have found two blocks using your pool software so far. I also run open ethereum pool as well. I have 55 on there.

**Comment by Serpent6877** [comment] 2017-11-20 19:06
Not sure what your config is. But a couple of things. 

"blockRefreshInterval": 120,

Need to lower this to 120ms or so. Otherwise you are missing out on blocks. The share balancing seems to be off as well. I am using the following:

  "ports": {
        "3333": {
          "listenAddress": "0.0.0.0",
          "difficulty": 0.1,
          "name": "GPU Mining",
          "varDiff": {
            "minDiff": 0.1,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        },
        "3334": {
          "listenAddress": "0.0.0.0",
          "difficulty": 1.0,
          "name": "High-End Multi GPU Mining",
          "varDiff": {
            "minDiff": 0.5,
            "maxDiff": null,
            "targetTime": 15,
            "retargetTime": 90,
            "variancePercent": 30
          }
        }
      },


I only use the high-end multi GPU for Nicehash. Even then it needs to be up more like 3.0. I am using port 3333 with a eight 1070 GPU miner doing 32Mh/s per GPU. It seems to level out around .765 per share.

**Comment by oliverw** [comment] 2017-11-20 21:01
@Serpent6877 *struck by lightning* Of course, with the extremely fast block times of ETH the refresh interval must be much lower.
