### ISSUE TITLE
[eth] System.FormatException: One of the identified items was in an invalid format.

### ISSUE THREAD

**Issue by lucas556** [coinfoundry/miningcore#310] opened 2018-04-14 08:21 UTC
### Description

parity 1.9.5
parity.sh
```console
parity --chain testnet --base-path /nodes/parity --db-path /nodes/parity/chains --mode active --no-ui --no-dapps --no-ipc --jsonrpc-hosts all --jsonrpc-interface all --jsonrpc-threads 4 --jsonrpc-port 8545 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --author "0x69cfbc1bdb4290f254194bf117f0265d09d01a70" --cache-size 512 --logging info --ws-port 8546 --ws-interface all --password "password.txt"
```

config.json
```console
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "",
        "logBaseDirectory": "",
        "perPoolLogFile": false
    },
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "myhost",
            "port": 3433,
            "user": "myuser",
            "password": "mypass",
            "database": "eth"
        }
    },
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
  "api": {
    "enabled": true,
    "listenAddress": "myip",
    "port": 4000
  },
    "pools": [{
        "id": "eth1",
        "enabled": true,
        "coin": {
            "type": "eth"
        },
        "address": "my eth address",
        "rewardRecipients": [{
                "type": "op",
                "address": "my eth address",
                "percentage": 0.5
        }],
        "blockRefreshInterval": 500,
        "jobRebroadcastTimeout":10,        
        "clientConnectionTimeout": 600,
      "shareBasedBanning":{
        "enabled":true,
        "time":600,
        "invalidPercent":50,
        "checkThreshold":50
      },

        "ports": {
            "3072": {
                "listenAddress": "127.0.0.1",
                "difficulty": 0.01,
                "varDiff": {
                    "minDiff": 0.05,
                    "maxDiff": null,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30,
                    "maxDelta":500
                }
            },
            "3073": {
                "listenAddress": "127.0.0.1",
                "difficulty": 5
            }
        },
        "daemons": [
            {
                "host": "127.0.0.1",
                "port": 8545,
                "user": "",
                "password": "",
                "portWs": 8546
            }
        ],
      "equihashMaxThreads":"",
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.01,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            },
            "coinbasePassword": "123456",
            "keepUncles": false,
            "keepTransactionFees": false
      }
    }
  ]
}
```

### Version
miningcore Release 23

### Additional Information

ETH testnet is Kovan.

![image](https://github.com/lucas556/mcpool-build/blob/master/config/eth-etc/mceth1.png?raw=true)

![image](https://github.com/lucas556/mcpool-build/blob/master/config/eth-etc/mceth2.png?raw=true)

**Comment by calvintam236** [comment] 2018-04-14 10:41
Duplicate of #301

**Closed by calvintam236** 2018-04-14 10:41 UTC
