### ISSUE TITLE
Pool fee calculation or show up issue.

### ISSUE THREAD

**Issue by jeong760** [coinfoundry/miningcore#71] opened 2017-11-14 11:14 UTC
Dears,

I've set 1% of the fee for BTC but it shows up a 1.15% of the fee for pool op when new block find.
So I think there is an error calculate a Pool fee. 

Mining Pool:            BTC 
Coin Type:              BTC 
Network Connected:      Main
Detected Reward Type:   POW
Current Block Height:   494246
Current Connect Peers:  41
Network Difficulty:     1364422081125.15
Network Hash Rate:      8193 PH/s
Stratum Port(s):        3333
**Pool Fee:               1.15%**

Regards,
John Ahn

**Comment by oliverw** [comment] 2017-11-14 13:58
Could you post the rewardRecipients part of your config?

**Comment by jeong760** [comment] 2017-11-14 21:22
"pools": [
    {
        "id": "BTC",
        "enabled": true,
        "coin": {
            "type": "BTC"
        },
        "address": "wallet address",
        "rewardRecipients": [
            {
                "type": "op",
                "address": "wallet address",
                "percentage": 1
            }
        ],

**Comment by pfeiflelukas** [comment] 2017-11-15 13:58
Are you taking into account the dev contribution? Mine is all correct when the server starts up

**Comment by oliverw** [comment] 2017-11-15 14:00
@jeong760 I'm confused. Does it show 1.5% or 1.15%? If its the latter then @pfeiflelukas is correct. Check the bottom of the README. I've just updated it to make things clearer.

**Comment by jeong760** [comment] 2017-11-16 01:45
@oliverw pool fee shows up 1.15% and I've changed 2% it displayed a 2.15% on BTC

**Comment by oliverw** [comment] 2017-11-16 07:05
devDonation = 0.15 does not remove the donation. devDonation = 0 does.

**Comment by jeong760** [comment] 2017-11-16 07:32
Just I wonder why only BTC does?

**Comment by oliverw** [comment] 2017-11-16 08:36
@jeong760 It's because the code contains a [donation address for BTC](https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinConstants.cs#L76) whereas it doesn't have one for more exotic coins. 

Closing this as working as intended.

**Closed by oliverw** 2017-11-16 08:36 UTC
