### ISSUE TITLE
Other pools get way more blocks. Configuration issue for shares?

### ISSUE THREAD

**Issue by Kukks** [coinfoundry/miningcore#150] opened 2018-01-03 16:27 UTC
Comparing my lyra2rev2 pool to other pools(yiimp based), they seem to get more blocks for the same ratio of hashrate. Is there some configuration I should be adjusting? 

Pool is reporting the following: 
```
Miners: 29
Hashrate: 3.99 GH/s
Valid Shares Per Second: 3
Current Block: 65176
Peers: 99
Network Difficulty 1.998543824405046 K
Network Hashrate 169.24 GH/s
```
block explorer for straks: https://straks.info
current difficulty around 3000-4000
my config:
```
      "4500": {
        "listenAddress": "0.0.0.0",
        "name": "SimpleDifficulty",
        "difficulty": 32.0,
        "varDiff": {
          "minDiff": 0.5,
          "targetTime": 15.0,
          "retargetTime": 60.0,
          "variancePercent": 90.0
        }
      },
      "7710": {
        "listenAddress": "0.0.0.0",
        "name": "SimpleDifficulty",
        "difficulty": 32.0,
        "varDiff": {
          "minDiff": 0.5,
          "targetTime": 15.0,
          "retargetTime": 60.0,
          "variancePercent": 30.0
        }
      },
      "4501": {
        "listenAddress": "0.0.0.0",
        "name": "HardDifficulty",
        "difficulty": 500.0,
        "varDiff": {
          "minDiff": 10.0,
          "targetTime": 15.0,
          "retargetTime": 60.0,
          "variancePercent": 50.0
        }
      }
    },
```

https://mpool.mooo.com/site/mining
https://datapaw.net/site/mining
https://www.cryptopool.xyz/site/mining

**Comment by oliverw** [comment] 2018-01-03 21:11
We need to get to the bottom of this. Could it be VarDiff related? Did you try connecting a miner to your own pool and compare the difficulty assigned to the difficulty when mining on the other pools you've mentioned?

**Comment by Kukks** [comment] 2018-01-04 07:19
I'll try and test tonight and see if I can find a difference.  I did switch the config of variancePercent to 90 from 30 and am seeing a little better performance but that's only speculation. The block time on straks is 60 seconds, could that affect anything? 

I just noticed my networks stats of the pool reporting this:
```
   "networkStats": {
      "networkType": "Main",
      "networkHashRate": 181716534221.55481,
      "networkDifficulty": 2046.5088761907671,
      "lastNetworkBlockTime": "2018-01-04T07:17:01.5742892Z",
      "blockHeight": 65176,
      "connectedPeers": 99,
      "rewardType": "POW"
    }
```
The block height seems to be stuck. This is probably another separate issue.

**Comment by oliverw** [comment] 2018-01-04 08:49
@Kukks Could you try this and report back?

```
 "blockRefreshInterval": 333,
 "jobRebroadcastTimeout": 10,
 
```

**Comment by Kukks** [comment] 2018-01-04 09:35
Just applied it now to the pool. Current block only updated on restart.

**Comment by oliverw** [comment] 2018-01-04 12:41
@Kukks The config changes were related to the block finding frequency. Could you try it? The stuck block height is a bug.

**Comment by Kukks** [comment] 2018-01-04 12:45
Pool has been running on these settings since you posted.  3 blocks since then.  Network hash is at 106gh/s and I only have ~2 so will see.

**Comment by oliverw** [comment] 2018-01-04 13:06
@Kukks Is that an improvement?

**Comment by Kukks** [comment] 2018-01-04 13:33
I'll give it till end of day to compare to yesterday. But it seems to be
doing better than yesterday

**Comment by oliverw** [comment] 2018-01-04 13:39
Ok, please keep me posted. I take this very seriously.

**Comment by Kukks** [comment] 2018-01-04 13:44
Will do. I do think adjusting the vardiff did a big difference though.

**Comment by Kukks** [comment] 2018-01-04 22:50
@oliverw Spoke too soon. No blocks found since 13:25 :(

**Comment by Kukks** [comment] 2018-01-05 06:49
@oliverw So it's been with no blocks for almost 18 hours now. My miners have fled like there was a plague. :(

**Comment by oliverw** [comment] 2018-01-05 07:53
I know that feeling all too well ;(

Lower <code>jobRebroadcastTimeout</code> to 3

**Comment by Kukks** [comment] 2018-01-05 08:00
Done.

**Comment by Kukks** [comment] 2018-01-05 08:13
@oliverw I've noticed that there are only 2 other pools left and they seem to have ~60gh/s and ~40gh/s in a ~100gh/s network hashrate. Could it simply be because of this?

**Comment by oliverw** [comment] 2018-01-05 08:14
There's always a problem with hashrate monopolies (or duopolies) like this, yes.

**Comment by oliverw** [comment] 2018-01-05 13:14
You could also try running the latest dev branch commit which contains some network low-level optimizations.

**Comment by StarbuckBG** [comment] 2018-01-07 01:22
Sorry for messing up here. Z-Nomp (node-stratum-pool) seem to suffer from the same problems in Bitcoin Gold. I have been digging a lot into this and:
- vardiff should not be a problem. When a share has difficulty lower than the required to create a block, it is a block candidate. Then it is validated by the daemon and beamed.
- if block refresh interval is really low it can make the daemon struggle in checking all the requests. 
- If jobRebroadcastTime is too low, pool struggles sending all the information.

I have been considering that there can be a problem in the daemon since other pool operators state that there is no such problem with other Z currencies, but however I have not found anything that could cause this kind of "bad luck".

**Comment by oliverw** [comment] 2018-01-07 08:44
@StarbuckBG Are you referring to your z-node-stratum-pool derivate created for BTG?

**Comment by StarbuckBG** [comment] 2018-01-07 08:55
Yes:
https://github.com/poolgold/z-nomp-bitcoin-gold
https://github.com/StarbuckBG/node-stratum-pool

**Comment by StarbuckBG** [comment] 2018-01-07 08:56
Initially we thought that it is a Redis issue, as Redis is single thread and in the way znomp is made it is really easy to fill it with data and it has major issues on the fetches. Hence we have made changes and it didn't improved. Rest of info is provided above.

**Comment by oliverw** [comment] 2018-01-07 08:58
Well, Miningcore is heavily multi-threaded I would be surprise if its a performance issue.

**Comment by StarbuckBG** [comment] 2018-01-07 09:00
The devs of pool.gold will migrate to it over the next week. Please check your gitter I have dropped some messages. I can give you some access so we can debug and improve under heavy load.

**Comment by oliverw** [comment] 2018-01-07 09:05
@StarbuckBG They will migrate to what?

**Comment by StarbuckBG** [comment] 2018-01-07 09:07
To Miningcore (:

**Comment by oliverw** [comment] 2018-01-07 09:10
@StarbuckBG Will do. One question though. I thought pretty much all pools are running https://github.com/StarbuckBG/node-stratum-pool and pool.gold is the biggest BTG pool. How can they have an issue with found blocks? And even if they do wouldn't everyone else have the same problem?

**Comment by StarbuckBG** [comment] 2018-01-07 09:19
On average pool has about 12% lower luck than the one supposed to have (based on 1 month calculations). All the z-nomp based pools are having that problem. There is a chat for investigating this problem in the BTG Slack with all the pool operators. It would be helpful if you join as well. And pool.gold is the 3rd largest BTG pool. First and second are respectively supernova and miningpoolhub. Both of them are using the python based pool stratum. This is why 8 devs are looking for the problem for the last 4 weeks and it is still unknown. 

There was a problem with the block validation (valid blocks shown invalid) and I have risen it as an issue to the repo owner (https://github.com/joshuayabut/equihashverify/issues/3 <https://github.com/joshuayabut/equihashverify/issues/3>). It was taking away 1 ever 25 blocks on average and I have found that by logging the shares with higher difficulty than the target for the network. Then I have found in the logs that some of the “block candidates” are rejected because of invalid equihash solution, but on the other hand when I validate manually the solution is correct. 

Znomp is good for small pools, for example if you have farm, but it is not for a product large pool. That is why all the pools that have more than 500 users must decide wether to switch to new software or not.

**Comment by oliverw** [comment] 2018-01-07 09:44
@StarbuckBG Send me a slack invite.

**Comment by StarbuckBG** [comment] 2018-01-07 09:47
Please check here - 
https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjY1MzkzMzUxNjY4LWM1YmQ4MjZhZTQxMWE1ZDQyNjA4N2QwZTkyZjYzMjhiMzdlMmVkNjQ3NzZlZDdmMDE4NWIyY2JmYzdjYmE2MzA

I’m there as @Martin, and I have a status “Out Sick”. There are impersonators, so beware. 

Thanks for all the help.

**Comment by oliverw** [comment] 2018-01-07 10:01
Signed in to slack as CoinFoundry

**Comment by StarbuckBG** [comment] 2018-01-07 10:03
Messaged there.

**Comment by Allar** [comment] 2018-01-15 02:14
I'm in the same boat. I got my own shitcoin, shares are being accepted, but in the same timeframe that p2pool and nomp had X mining effort, miningcore with the same mining effort solved almost 5% of blocks. I have a relatively closed environment and am able to coordinate mining efforts, and it doesn't seem to be an issue like 'another mining pool is huge and therefore is taking all the blocks'. I can hotswap MiningCore out on a pool server with nomp/p2pool, and end up seeing a lot more solved blocks with either.

**Comment by StarbuckBG** [comment] 2018-01-15 07:18
Can you please check debug.log of the coin daemon and grow for acceptBlock. 

I had problems with incorrect SegWit blocks, then with Orphaned blocks and went to zeroMQ external stratum option and it is working beautifully.

**Comment by Kukks** [comment] 2018-01-15 07:31
@StarbuckBG How did you set up the external stratum config and with what software?

**Comment by StarbuckBG** [comment] 2018-01-15 07:41
1. You must get one of the node-stratum-pool repos for the coin that you mine - https://github.com/coinfoundry <https://github.com/coinfoundry>

2. In the node-stratum-pool you must make a config.json file. You can follow the instructions on the repo for the config file, but be aware that is must be in a JSON file, not on main.js file. Also add the “coin” : {} information inside the config JSON.

3. Add this to config.json:

	"publisherSocket": "tcp://<StratumMachineIP(this machine. It must be the external IP)>:4001",
	"publisherTopic": “topic1”

4. Inside COIN config of miningcore config file you add
	"externalStratum": true,
        "externalStratumZmqSocket" : "tcp://<ip from point 3>:4001",
        "externalStratumZmqTopic" : “topic1"

5. you start with node path/to/lib/index.js path/to/config.json (mind that the path to config.json must be relative to index.js, not the current directory).

Be aware that if you enable external stratum, people will not be able to connect to the current pool. Only 1 is working - wether external stratum or miningcore stratum.

**Comment by Kukks** [comment] 2018-01-15 08:01
@StarbuckBG Ah, so the external stratum setting only works with nomps' stratum.  It wouldn't be able to hook up to say, yiimp?

**Comment by oliverw** [comment] 2018-01-15 08:10
@Kukks The external stratum stuff is for a couple of NOMP pool derivates ([this](https://github.com/coinfoundry/z-node-stratum-pool), [this](https://github.com/coinfoundry/node-stratum-pool) and this [this](https://github.com/coinfoundry/nodejs-pool) I was experimenting with when researching an issue similar to this one.

**Comment by StarbuckBG** [comment] 2018-01-15 08:26
@Oliver BTG pool runs fine on the external stratums with the provided steps to setup. 

When you have take please check the last issue I have opened. I can give you access to the server if needed. I’m able to reproduce it each time.

**Comment by Gadflyii** [comment] 2018-01-23 05:27
So what this fixed, or is it still an open issue?

**Comment by Kukks** [comment] 2018-01-23 09:00
I'm leaving this open as I can't tell right now since my hashrate is too low for the current Straks network hashrate to make assumptions. I still think there is some sort of performance issue with finding blocks when compared to the yiimp solution.

**Comment by oliverw** [comment] 2018-01-23 11:28
@Kukks I'm calling for some concerted effort to figure this out.

- Can we all agree (it's okay if we don't) that the problem is not related to share validation/submission as a bug in that area would result in high reject rates which would be easy to spot, right?
- I see two areas however, where problems could lurk:
  - Vardiff: I've seen reports of people mining against a Miningcore getting lower difficulties assigned over time than for example with a node-stratum-pool. In theory it shouldn't make that much of a difference as with higher difficulties the pool just received fewer shares with higher difficulty. Opinions?
  - Job Management: If there's a bug in the pools book-keeping about miner jobs, there could be a problem with duplicate work assignments for the miners. The fact that the implementation for that is not coherent accross the various supported coin families (Bitcoin, Cryptonote (Monero etc.) and Ethereum) does not make it easier to validate that.

**Comment by Gadflyii** [comment] 2018-01-23 17:05
@oliverw I will start to go over the job management and test it

**Comment by Allar** [comment] 2018-01-23 22:03
I'm not smart enough to be involved, but I've had this reoccuring issue reported (haven't been able to reproduce myself) that may be related to job management?

Using nomp/p2pool, the following behavior did NOT occur, but appears to be happening with MiningCore.

Miners who mine actively for long periods of time will stop getting payments, and also stop gaining pending shares, even though they are actively mining. Restarting the miner and reconnecting to the pool generally fixes the problem. Multiple people on my pool have reported this and have transaction logs (backed by our block explorer) that show no payments when they ought to be still being paid and earning shares. The mining pool still counts these miners as connected to the pool however when pulling the worker count stat.

Regarding total block count, we've switched everyone to our miningcore server and we no longer have gaps in mining blocks, but it appears our average block difficulty is generally lower as well than when we used other pool software. Still not really sure whats going on, and maybe its just a quirk of our blockchain, but I'm definitely getting more consistent reports of bad behavior by the pool from miners than with any other pool server.

**Comment by oliverw** [comment] 2018-01-23 22:16
> Miners who mine actively for long periods of time will stop getting payments, and also stop gaining pending shares, even though they are actively mining.

Well, I had to deal with a lot of those complaints on coinfoundry.org (formerly poolmining.org) and in retrospective every single case was either that the person stopped mining at some point and had a misconfigured miner.  Take our Dash for [for example](https://coinfoundry.org/pool/dash). The pool has paid out close to half a million dollars in coins so far and ASIC miners are very, very concerned about payments and ROI. You can bet that if there was problem with the payment system, those guys would have drawn the pitchforks and left long ago.

**Comment by oliverw** [comment] 2018-02-08 08:39
I wanted to get to the bottom of this. Therefore I decided to test this on a production pool with high enough and consistent hashrate. Therefore I chose [Coinfoundry's Dash Pool](https://coinfoundry.org/pool/dash). Throughout the past two weeks I switched back and forth between Miningcore's internal stratum and an [external one](https://github.com/coinfoundry/node-stratum-pool) which is a stripped down version of the node-stratum-pool that only processes shares and block submissions. 

The net result was that I was unable to find any significant advantage of using node-stratum-pool over Miningcore's internal stratum. In fact judging from the average block effort, Miningcore had a slight advantage. One thing to remember is that you should utilize streaming block updates by all means. I've [updated the Wiki to reflect this](https://github.com/coinfoundry/miningcore/wiki/Configuration) (see zmqBlockNotifySocket and wsPort).

**Closed** 2018-03-23 21:24 UTC
Labels: question

**Comment by Gadflyii** [comment] 2018-04-09 22:06
@oliverw  Quick question, how do you configure MC to use the node-stratum-pool ?
