### ISSUE TITLE
zcash Block 286404 submission failed with: tx-overwinter-active

### ISSUE THREAD

**Issue by zheng9980419** [coinfoundry/miningcore#386] opened 2018-09-06 10:51 UTC
json-rpc:
Unsupported RPC request: {"jsonrpc":"2.0","method":"mining.submit","params":["tmBwYF8DTzKzKoqmiUjTAgkKJiejATZZzo1.3667","00000010","4106915b","67ff940000000000000000000000000000000000000000000000000000","fd4005000706a9cc45542aa6a750b4a210b1a46dccb44e3e20f426091492f7e7ed5b25e4f865b5ce0e9a77659103783e2140156d7995595349cfd08688f888de0ea20c4186f3bf4aa23730153343142d97c6bd18fd8a3f010766279de81603d90000481504b0d83e634c663f5fba0df9d05ddb2d6ca46896ded4f62a7463545b831574319896cf1da35859e7aed8e256ea38045518b9287a8cbaed0bf1553075c4705bae24f5b69a50ed4a02ebc31c01c0cc948cf7e0bd70b8eb1d4e028b56de2e2d83e055e06101e66a7a5f56730a4f81c9de544e04cf58cc234daab0e139d34913a6afc912927f909e1995d8e07ca4e5dd46c4f3e277dd20c7316fbeabaf06c2c1b21ad206d3fa1755c315b5e21990b85b848823e7bb166395ef90dca1b3836651a60ce95a0d20ac11702c65c5cf6185c11de15ef1a2dd5082f2eb8e9418c4f754fc10dfa9744a03955cc2a17ec4469de1ed029ab93248ce142f3ad56055947944032b557eb9c20c6d8d9e6ad6ea27ba8185f3d1bb9b71efb71b71d0104ed1a1d5d6ea3d6982b410972d10119c436cfb5815f45f09bb4594912d7ef2c8ac4cc2017f695d8a30095ae62f1f4c67d0deec619f05ca9aca304a7a46811eb6336e4e99626da06c0488e07e2cce9bb09c702f16ed293ecfb530fdaa81923f95e4b7a29414db4fda33ef15e0b0e32a9f4a3bf368812c96da6d7355defc05984f9c0e56954d783fa0ab6236c34d071ccc8fad460e129a36288b134c04c497ab4c5186dbef19dd770bcc57f237e2b733ba1f129504b6af6179b859dae6172ac50a55199469bde352b2b741e0b3239f1dd1530ae938ee3d56395dde94c0ff1054d358ef35d106013cdf2fe3d156ef831d63d5a6aefec5e1dbe6ef6f411c30af4028d72a954ea378826af6e56a3bdbf25bcc2534e92ad855a456fdf3b27bd99a6110a752895fef00748a5453aa00f79e35207f1bf9cc4d6c105406151ad8f681aaa2afe5cbb3d343734955d5d2a9d8a8b7071bd83bb087d1fd35738389052c14899aa19fa18d1caf9f1ccd07591d65fcf2685f2c491d85cbb1d615099f84547412a37fa1f7327fcf4d8114af702e262531528cd318da2da55c9667d68bf0e9e226ee56d1460cfdc11a53f5a0d9da6a917ac12dee799573d398fe162540d507eaaa0f6d48b9441ffa8bc6a5abb8edd101ad3f0a21163eb11faec7eb2370df6e4d889fd5f7070bdab42b13869352d3b936a66e8f4369fcdce61202b73f818fd687a9fd41448019f4e25b3a3f3c63f4068d096b0f1343477c5782c4f64bf4b5f6bd53ccca0322894b984e4ecfa3d361de92e5ff5537f5d821890e835345c1cea2e1c7bae1afd6e0519cae4cfffa8633bfe263e8b575fdfeeef4a5e1b48cba19261617854d7f8abccdd36329d341853543fb8867686e7b7bab00fffee93003a493632fc39116f5963a06191a7b8d1c3e2c4645a8c4595ebf727c0d3ba95cb7bc6bcf420ae05371a7e26ff395518887cbf9178b9dc8fefed91dcb4450190f55369ac702a84669e67209de1a4d0b0f31bd30cc04d4b6d568f2ee076e78ade125ef9332189c46b40e28b823d62243097e3a7cc930e19bab46152fbd422e88464d2b08d159a28eee61365659577f1f5c25ce6bec9859f20ef29710c56cb4b68a79b75a025d59ea16a7be9366cb53b79436db8101a88aafbf30299d90fc57c0fdde40e4456065f0a5d9a4d1ad490265396c1207c3e97550d416796b7cc6b5fddc911003827e3863e16647b446314ab0a32a127a3c159ec90c32e1e84f4eb2835762e2d915448e1185b532411d0c57112f6f72a1c7d3e32349e9b9a49506de588d3e1b9cec67ea282c55dfa004fb6c2f2e7567c871a65d1e1f6fd191d4d2e4b6cec5d66b4e4989f64757541a"],"id":1358}
------------------------------------------------------------------------------------------------------
[2018-09-06 18:49:42.1087] [I] [zec1] [Bitcoin Job Manager] Submitting block 286404 [000038b23cb26dd0f8fa9c1d0a134315ba3018b03dbfd628e57f050de8fadad3]
[2018-09-06 18:49:42.1223] [W] [zec1] [Bitcoin Job Manager] Block 286404 submission failed with: tx-overwinter-active

-----------------------------------------------------------------------------------------------------------
wallet:
2018-09-06 10:49:42 ERROR: ContextualCheckTransaction: overwinter is active
2018-09-06 10:49:42 ERROR: ProcessNewBlock: AcceptBlock FAILED
2018-09-06 10:49:42 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)

**Comment by zheng9980419** [comment] 2018-09-06 10:52
Very urgent.

**Comment by zheng9980419** [comment] 2018-09-06 10:53
wallet version 2.0

**Comment by calvintam236** [comment] 2018-09-14 06:05
Please use the following format to file an issue. Thank you for your cooperation.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expect to happen]

### Actual behavior

[What actually happens]

### Reproduces how often

[What percentage of the time does it reproduce?]

### Version

If you are using released version, please state your version.
If you are using clone from `dev` branch, please state commit hash of your copy.
Also, please include the OS name and version you're currently running.

### Additional Information

Any additional information, log, configuration or data that might be necessary to reproduce the issue.

**Comment by calvintam236** [comment] 2018-09-14 06:06
Duplicate of #374. Closing this.

**Closed by calvintam236** 2018-09-14 06:06 UTC
Labels: need more infomation
