### ISSUE TITLE
Mine DGB Groestl but stratum reject share with LowDifficultyShare

### ISSUE THREAD

**Issue by shwuhk** [coinfoundry/miningcore#182] opened 2018-01-17 15:37 UTC
I start MiningCore and put 
```
      "coin": {
        "type": "DGB",
        "algorithm": "groestl"
      },
```
in the config file.
Mine with ccminer and algo set to ```"algo" : "myr-gr",```. Mine successfully in other pools but not in MiningCore. May I know is there something wrong? Thanks.

**Comment by oliverw** [comment] 2018-01-23 11:21
groestl != groestl-myriad

**Comment by oliverw** [comment] 2018-01-23 13:21
@shwuhk I see what you mean. Looks like the groestl implementation used by DGB-Groestl is slightly different than what Groestlcoin uses.

**Comment by oliverw** [comment] 2018-01-26 19:25
@shwuhk Can you describe the problem(s) you are facing?

**Comment by shwuhk** [comment] 2018-01-27 16:37
I use ccminer to mine DGB-Groestl. However, all the shares submitted were rejected by MC.

**Comment by oliverw** [comment] 2018-03-23 20:57
@shwuhk Should be fixed in Release 21. Can you confirm the issue is still present?

**Comment by oliverw** [comment] 2018-10-11 13:43
Closing due to inactivity.

**Closed by oliverw** 2018-10-11 13:43 UTC
Labels: need more infomation
