### ISSUE TITLE
Workflow for adding a new Coin

### ISSUE THREAD

**Issue by bjorntheart** [coinfoundry/miningcore#166] opened 2018-01-11 17:34 UTC
I'd very much like to contribute to this project.
The only place I think I can add value, to source code specifically, is by adding support for new coins.
Can someone help me understand the workflow for adding new coins?
I'd like to know what code needs to change and why?
What files should I add, if any?

Please fill in the blanks for anything else I am missing.

**Comment by calvintam236** [comment] 2018-01-11 17:35
Duplicate of #85.

**Comment by bjorntheart** [comment] 2018-01-11 17:35
Sorry, didn't see that

**Closed by calvintam236** 2018-01-11 17:35 UTC
